fit_domain: Pump
features:
- temperature
- pressure
- vibration
- humidity
normalization: zscore
mean:
  temperature: 70.634028
  pressure: 35.629021
  vibration: 1.613323
  humidity: 50.197351
std:
  temperature: 15.781869
  pressure: 10.501268
  vibration: 0.700299
  humidity: 11.874382
